# Global configuration applicable to all environments
server:
  port: 8084

# Kafka configuration
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
