# Global configuration applicable to all environments
server:
  port: 8082

# Database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskdb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Security configuration
security:
  jwt:
    secret-key: mySecretKey
    expiration-time: 86400000 # 1 day in milliseconds
